### ISSUE TITLE
ImportError fastNLP

### ISSUE THREAD

**Issue by lxianl455** [NUSTM/VLP-MABSA#16]
我运行sh 15_pretrain_full.sh，但是出现以下错误
`7e-5
Traceback (most recent call last):
  File "MAESC_training.py", line 19, in <module>
    from src.model.MAESC_model import MultiModalBartModel_AESC
  File "/home/jovyan/multimodal_aspect_sentiment/VLP-MABSA/src/model/MAESC_model.py", line 2, in <module>
    from fastNLP.modules import Seq2SeqEncoder, Seq2SeqDecoder, State
ImportError: cannot import name 'Seq2SeqEncoder' from 'fastNLP.modules' (/home/jovyan/environment/anaconda3/body/envs/vlpmabsa/lib/python3.7/site-packages/fastNLP/modules/__init__.py)`

**Comment by lyhuohuo** [comment]
直接使用pip install fastnlp安装即可，我们使用的默认版本
